Explicitly Ignore return value in consoleLogHandler() from writev()
Fixes the following build error:
 logging/source/RialtoLogging.cpp:113:34:
 error: ignoring return value of 'ssize_t writev(int, const iovec*, int)',
 declared with attribute warn_unused_result [-Werror=unused-result]
     writev(STDERR_FILENO, iov, 5);
                                  ^
cc1plus: all warnings being treated as errors

Signed-off-by: Damian Wrobel <dwrobel@ertelnet.rybnik.pl>

--
Summary: Explicitly ignore return value in consoleLogHandler() from writev()
Type: fix
Owner: Damian Wrobel
Test Plan: None
Dependencies and Impacts: None